// src/main/resources/static/js/components/CartAdd.vue
<template>
  <div class="add-to-cart">
    <div class="mb-5">
      <div class="input-group mb-3" style="max-width: 220px;">
        <div class="input-group-prepend">
          <button id="quantity-minus" v-on:click="decrementQuantity()" class="btn btn-outline-primary js-btn-minus" type="button">&minus;</button>
        </div>
        <input type="text" class="form-control text-center" :value="quantity" @input="quantityTextEntered">
        <div class="input-group-append">
          <button id="quantity-plus" v-on:click="incrementQuantity()" class="btn btn-outline-primary js-btn-plus" type="button">&plus;</button>
        </div>
      </div>
    </div>
    <p><a v-on:click="addToCart()" :disabled="!instock" href="#" class="buy-now btn btn-sm height-auto px-4 py-3 btn-primary">Add To Cart</a></p>
  </div>
</template>

<script src="./CartAdd.js"></script>

<style scoped>
</style>

// src/main/ui/src/app/cart/cart-add/cart-add.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { ActivatedRoute, Router} from "@angular/router";

import { NgbModal, ModalDismissReasons } from '@ng-bootstrap/ng-bootstrap';

import { CartService } from "../../_services/cart.service";

@Component({
  selector: 'app-shopping-cart-add',
  templateUrl: './cart-add.component.html',
  styleUrls: ['./cart-add.component.css']
})
export class CartAddComponent implements OnInit {
  @Input() pid: string;
  @Input() inStock: boolean = true;

  @Output() quantity: number = 1;

  closeResult: string = '';

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private modalService: NgbModal,
    private cartService: CartService
  ) { }

  ngOnInit(): void { }

  incrementQuantity() {
    this.quantity++;
  }

  decrementQuantity() {
    if (this.quantity > 0) this.quantity--;
  }

  quantityTextEntered(event: any) {
    this.quantity = event.target.value;
  }

  addToCart(content) {
    this.cartService.add(this.pid, this.quantity);
    this.modalService.open(content, {ariaLabelledBy: 'modal-basic-title'}).result.then((result) => {
      if (result === "buy") {
        this.router.navigate( ['/cart'])
      } else if (result === "continue") {
        this.router.navigate(['/products', { }]);
      }
    }, (reason) => {
    });
  }

  private getDismissReason(reason: any): string {
    if (reason === ModalDismissReasons.ESC) {
      return 'by pressing ESC';
    } else if (reason === ModalDismissReasons.BACKDROP_CLICK) {
      return 'by clicking on a backdrop';
    } else {
      return `with: ${reason}`;
    }
  }

}

<ng-template #content let-modal>
  <div class="modal-header">
    <h4 class="modal-title" id="modal-basic-title">Item added to your shopping cart</h4>
    <button type="button" class="close" aria-label="Close" (click)="modal.dismiss('Cross click')">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <form>
      <div class="form-group">
        <p>One fine body&hellip;</p>
      </div>
    </form>
  </div>
  <div class="modal-footer">
    <div class="container">
      <div class="text-center">
        <div class="btn-group-vertical p-2">
          <button type="button" class="btn btn-outline-primary m-2" (click)="modal.close('buy')">Buy now</button>
          <button type="button" class="btn btn-outline-secondary m-2" (click)="modal.close('continue')">Continue shopping</button>
        </div>
      </div>
    </div>
  </div>
</ng-template>

<div class="add-to-cart">
  <div class="mb-5">
    <div class="input-group mb-3" style="max-width: 220px;">
      <div class="input-group-prepend">
        <button id="quantity-minus" (click)="decrementQuantity()" class="btn btn-outline-primary js-btn-minus" type="button">&minus;</button>
      </div>
      <input name="quantity" type="text" class="form-control text-center" (change)="quantityTextEntered($event)" [(ngModel)]="quantity">
      <div class="input-group-append">
        <button id="quantity-plus" (click)="incrementQuantity()" class="btn btn-outline-primary js-btn-plus" type="button">&#43;</button>
      </div>
    </div>
  </div>
  <!-- [attr.disabled]="!inStock" -->
  <p><button type="submit" (click)="addToCart(content)" class="buy-now btn btn-sm height-auto px-4 py-3 btn-primary">Add To Cart</button></p>
</div>
