// frontend/src/app/products/new-products/new-products.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { ProductService } from 'src/app/_services/product.service';
import { Product } from 'src/app/models/product';

@Component({
  selector: 'app-new-products',
  templateUrl: './new-products.component.html',
  styleUrls: ['./new-products.component.css']
})
export class NewProductsComponent implements OnInit {
  @Input() page: number = 1;
  @Input() limit: number = 3;
  products!: Product[];

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private productService: ProductService
  ) { }

  ngOnInit(): void {
    this.getProducts();
  }

  getProducts(): void {
    this.productService.getProducts(this.page, this.limit)
      .subscribe(products => this.products = products);
  }

  gotoProducts(product: Product) {
    const productId = product ? product.id : null;
    this.router.navigate(['/products', { id: productId, foo: 'foo' }]);
  }

}
<div>
    <div class="site-section bg-light">
      <div class="container">
        <div class="row">
          <div class="title-section text-center col-12">
            <h2 class="text-uppercase">New Products</h2>
          </div>
        </div>
        <div class="row">
          <div *ngFor="let product of products" class="col-sm-6 col-lg-4 text-center item mb-4">
            <span *ngIf="product.onSale" class="tag">Sale</span>
            <a [routerLink]="['/products/',product.id]">
              <span *ngIf="product.image">
                <img [attr.src]="'/assets/img/products/' + product.image" alt="Image" class="img-fluid">
              </span>
              <span *ngIf="!product.image">
                <img [attr.src]="'/assets/img/awaiting-image-sm.png'" alt="Image" class="img-fluid">
              </span>
            </a>
            <h3 class="text-dark"><a [routerLink]="['/products/',product.id]">{{ product.name }}</a></h3>
            <p *ngIf="product.onSale" class="price">
              <del>{{ product.price | currency }}</del> &mdash; {{ product.salePrice | currency }}
            </p>
            <p *ngIf="!product.onSale" class="price">
              {{ product.price | currency }}
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>

// src/main/resources/static/js/components/NewProducts.vue
<template>
  <div>
    <div class="site-section bg-light">
      <div class="container">
        <div class="row">
          <div class="title-section text-center col-12">
            <h2 class="text-uppercase">New Products</h2>
          </div>
        </div>
        <div class="row">
          <div v-for="product in products" :key="product.id" class="col-sm-6 col-lg-4 text-center item mb-4">
            <span v-if="product.onSale" class="tag">Sale</span>
            <a v-bind:href="'/products/' + product.id">
              <span v-if="product.image">
                <img v-bind:src="'/img/products/' + product.image" alt="Image" class="img-fluid">
              </span>
              <span v-else>
                <img v-bind:src="'/img/awaiting-image-sm.png'" alt="Image" class="img-fluid">
              </span>
            </a>
            <h3 class="text-dark"><a v-bind:href="'/products/' + product.id">{{  product.name }}</a></h3>
            <p v-if="product.onSale" class="price">
              <del>{{ currencySymbol }}{{  product.price }}</del> &mdash; {{ currencySymbol }}{{  product.salePrice }}
            </p>
            <p v-else class="price">
              {{ currencySymbol }}{{  product.price }}
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script src="./NewProducts.js"></script>

<style scoped>
</style>
